### ISSUE TITLE
Q: how is the `subitems_url` maintained?

### ISSUE THREAD

**Issue by umlaeute** [guysoft/pi-imager-web#9]
i see that the JSON for adding a new distro includes a `subitems_url` that contains the actual links to the the downloadable images (and checksums and whatnot), e.g.:

https://github.com/guysoft/pi-imager-web/blob/13b97ae0d616cbcd5670eb2b0d1cc3912af6a9ff/src/distros_list/ElectricSheepPi.json#L9

i wonder how these subitems are maintained.

if i were to add my own distro, should i self-host this JSON file? are there any documents describing (or scripts generating) this files?

**Comment by guysoft** [comment]
It's generated in my case it takes snipplets from here:
https://github.com/guysoft/CustomPiOS/blob/devel/src/make_rpi-imager-snipplet.py

And strings them together using this:
https://github.com/guysoft/unofficialpi/blob/main/src/create_rpi-imager-distro.py

You will need to adapt it to the CI/CD you are using.

There is also this method using a github action which you can take ideas from:
https://github.com/guysoft/OctoKlipperPi/blob/main/.github/workflows/build.yml#L194

**Comment by umlaeute** [comment]
thx
